### ISSUE TITLE
How do I run QT?

### ISSUE THREAD

**Issue by kech1004** [Mindinventory/AltCoin-Generator#1]
How do I run QT?

**Comment by malvikiran** [comment]
If you are using linux server then you have to run like below command:

>> Go to folder directory.
>> ./altcoin-qt

**Comment by kech1004** [comment]
Thank you for the reply.

And do you know how to change the x11 algorithm?

**Comment by kech1004** [comment]
Thank you. I would like to create a coin that contains master node functions like dash or pivx. What should I fix here?

**Comment by kech1004** [comment]
Thank you. I would like to create a coin that contains master node functions like dash or pivx. What should I fix here?

**Comment by malvikiran** [comment]
Hello Kech,

Actually, MasterNode is different then altcoin creation fork. If you want to create masterNode fork then you have to follow below steps:

`Hot MasterNode VPS Setup(Part 1) with Linux CLI only wallet
This will run 24/7 and provide services to the network via TCP port 9020 for which it will be rewarded with coins. It will run with an empty wallet reducing the risk of loosing the funds in the event of an attack.

1. Get a VPS server from a provider like Vultr, DigitalOcean, Linode, Amazon AWS, etc.
Requirements:

Linux 64 bit, (e.g. Ubuntu 16.04) running on a server in the cloud 24/7. e.g: VPS such as Vultr, Amazon EC2 instance, Azure instance
Dedicated Public IP Address
Recommended at least 1GB of RAM and 20GB of disk space
Basic Linux skills
You can get servers like this for $5 a month and can run 3,4 MasterNode wallets from different coins if the monthly cost is a concern.

2. Login via SSH into the server and type the following command in the console as root:
If you are using Windows, PuTTY is a very good SSH client that you can use to connect to a remote Linux server. If you are running a VPS from Vultr or similar, you need to use SSH such as putty if you want to copy and paste these commands otherwise you will have to type them all out!

3. Configure swap to avoid running out of memory if you don't have a swap :
fallocate -l 3000M /mnt/3000MB.swap
dd if=/dev/zero of=/mnt/3000MB.swap bs=1024 count=3072000
mkswap /mnt/3000MB.swap
swapon /mnt/3000MB.swap
chmod 600 /mnt/3000MB.swap
echo '/mnt/3000MB.swap  none  swap  sw 0  0' >> /etc/fstab
4. Allow SSH and MasterNode p2p communication port through the OS firewall:
ufw allow 22/tcp
ufw limit 22/tcp
ufw allow 9020/tcp
ufw logging on
ufw --force enable
If you are running the MasterNode server in Amazon AWS or if additional firewalls are in place, you need to allow incoming connections on port TCP 9020 from any IP address.

5. Install the Rupaya CLI wallet. Always download the latest release available, unpack it
Download and unpack the Rupaya wallet binaries by running the following commands:

This command uses a short github url to download rupaya-4.1.0-x86_64-linux.tar.gz and unpack the binaries in the PATH:

wget -qO- https://git.io/vpeSF | sudo tar xvz -C /usr/local/bin/
rupayad
You'll get a start error like Error: To use rupayad, or the -server option to rupaya-qt, you must set an rpcpassword in the configuration file. It's expected because we haven't created the config file yet.

The service will only start for a second and create the initial data directory(/root/.rupaya/).

6. Edit the MasterNode main wallet configuration file:
nano /root/.rupaya/rupaya.conf
Enter this wallet configuration data and change accordingly:

rpcuser=<alphanumeric_rpc_username>
rpcpassword=<alphanumeric_rpc_password>
rpcport=7020
rpcallowip=127.0.0.1
rpcconnect=127.0.0.1
rpcbind=127.0.0.1
maxconnections=512
listen=1
daemon=1
externalip=<public_mn_ip_address_here>:9020
masternodeaddr=<public_mn_ip_address_here>:9020
addnode=seeds.rupx.io
You can right click in SSH (putty) to paste all of the above

Exit the editor by CTRL+X and hit Y + ENTER to commit your changes.

This is a real example:

rpcuser=rupxuser
rpcpassword=someSUPERsecurePASSWORD3746375620
rpcport=7020
rpcallowip=127.0.0.1
rpcconnect=127.0.0.1
rpcbind=127.0.0.1
maxconnections=512
listen=1
daemon=1
externalip=199.247.10.25:9020
masternodeaddr=199.247.10.25:9020
addnode=seeds.rupx.io
The IP address (199.247.10.25 in this example) will be different for you. Use the ifconfig command to find out your IP address, normally the address of the eth0 interface. We are going to use this IP and port (9020) in the Cold Wallet setup(Step 2) as well.

7. Start the service and let's obtain the value for masternodeprivkey:
rupayad
Wait a few seconds then run this command to generate the masternode private key:

rupaya-cli masternode genkey
Copy to your clipboard the value returned, similar to this:

87LBTcfgkepEddWNFrJcut76rFp9wQG6rgbqPhqHWGvy13A9hJK
Edit the configuration file again:

nano /root/.rupaya/rupaya.conf
Add these two lines at the end of the file. The second line is taking the value you received from the rupaya-cli masternode genkey command:

masternode=1
masternodeprivkey=<your_masternode_genkey_output>
In my case this was:

masternode=1
masternodeprivkey=87LBTcfgkepEddWNFrJcut76rFp9wQG6rgbqPhqHWGvy13A9hJK
Exit the editor by CTRL+X and hit Y + ENTER to commit your changes.

Stop the wallet and wait 2 minutes before attempting a start:

rupaya-cli stop && sleep 120
rupayad
8. Verify that the wallet is synching the blockchain:
Run this command every few mins until you see the blocks increasing.

rupaya-cli getinfo
We can now go to the next step while this wallet syncs up with the network and gets social with the other MasterNodes.

`

**Comment by kech1004** [comment]
I want to add the master node function to the coin created by the Altcoin generator.
